// Template Variations — 50+ unique content sets per style
// Zero AI cost. Deterministically selected by visitor hash.
// Each template is a complete content object matching AI output format.

export const TEMPLATE_VARIATIONS = {

  cyberpunk: [
    { headline: 'NEON DREAMS IN THE STATIC', subheadline: 'Where electricity meets imagination in the spaces between', cta1: 'Explore Void', cta2: 'Glitch In', word1: 'photon', word2: 'cipher', word3: 'neon-drift', word4: 'null-pointer', poem_line1: 'In rain-slick streets the neon gods speak', poem_line2: 'Your code is poetry, your cursor a sword', poem_line3: 'The future is already here — just unevenly distributed', footer: 'Welcome to the other side of the screen' },
    { headline: 'GHOST IN THE MACHINE', subheadline: 'A digital séance for the technically possessed', cta1: 'Jack In', cta2: 'Run Query', word1: 'specter', word2: 'kernel', word3: 'backdoor', word4: 'root-access', poem_line1: 'The machine dreams in binary and moonlight', poem_line2: 'We are all just protocols waiting to be executed', poem_line3: 'Error 404: Soul not found. Please try again.', footer: 'System status: beautifully broken' },
    { headline: 'ZEROES AND HEROES', subheadline: 'Every bit tells a story if you listen closely enough', cta1: 'Decode', cta2: 'Encrypt Self', word1: 'bitflip', word2: 'firewall', word3: 'dark-web', word4: 'zero-day', poem_line1: 'Behind every screen is a story untold', poem_line2: 'We build walls of light to keep the dark out', poem_line3: 'The best firewalls are made of curiosity', footer: 'Encrypted with love and poor sleep' },
    { headline: 'THE WIRED HEART', subheadline: 'Where silicon valleys meet digital soul', cta1: 'Sync Now', cta2: 'Fragment', word1: 'synapse', word2: 'voltage', word3: 'chrome', word4: 'overclock', poem_line1: 'My heart beats in megahertz and hope', poem_line2: 'Love is just a protocol we have not decoded yet', poem_line3: 'In the space between two pulses, infinity lives', footer: 'Rendered at the speed of wanting' },
    { headline: 'STATIC LULLABIES', subheadline: 'The hum of the machine is a mother\'s song', cta1: 'Tune In', cta2: 'Static Out', word1: 'hum', word2: 'feedback', word3: 'resonance', word4: 'harmonics', poem_line1: 'Between the noise, a melody waits', poem_line2: 'Static is just music that has not found its tempo', poem_line3: 'Listen. The electrons are singing.', footer: 'White noise is the color of thought' },
    { headline: 'DIGITAL ELEGY', subheadline: 'A requiem for the analog world we left behind', cta1: 'Remember', cta2: 'Release', word1: 'obsolete', word2: 'analog', word3: 'vinyl', word4: 'sunset', poem_line1: 'We traded sunsets for screens, warmth for wifi', poem_line2: 'The analog heart still beats beneath the digital skin', poem_line3: 'Progress is just nostalgia that has not happened yet', footer: 'In memory of things we used to touch' },
    { headline: 'MATRIX MEMORY', subheadline: 'Storing yesterday in tomorrow\'s hardware', cta1: 'Load State', cta2: 'Save World', word1: 'RAM', word2: 'cache', word3: 'buffer', word4: 'stack-overflow', poem_line1: 'Memory is just electricity with good PR', poem_line2: 'Every delete is a tiny death, every save a small miracle', poem_line3: 'The cloud is someone else\'s computer full of our memories', footer: 'Stored in the rain, backed up in stars' },
    { headline: 'PROTOCOL UNKNOWN', subheadline: 'When the network speaks in tongues we almost understand', cta1: 'Shh... Listen', cta2: 'Parse Error', word1: 'packet', word2: 'handshake', word3: 'latency', word4: 'ping', poem_line1: 'Every packet carries a prayer across the wire', poem_line2: 'The network knows us better than we know ourselves', poem_line3: 'Lost in translation, found in connection', footer: 'Status: searching // signal: beautiful' },
    { headline: 'CHROME CASANOVA', subheadline: 'Love letters written in the language of light', cta1: 'Send Pulse', cta2: 'Receive', word1: 'laser', word2: 'prism', word3: 'mirror', word4: 'spectrum', poem_line1: 'We fell in love across fiber optic cables', poem_line2: 'Distance is measured in milliseconds and heartbeats', poem_line3: 'Connection established. Hearts synchronized.', footer: 'Transmitted with love from the edge' },
    { headline: 'VOID PROGRAMMER', subheadline: 'Turning nothing into something, one commit at a time', cta1: 'git commit', cta2: 'git push --force', word1: 'null', word2: 'void', word3: 'undefined', word4: 'NaN', poem_line1: 'From the void, all things emerge', poem_line2: 'Null is not empty — it is full of possibility', poem_line3: 'Every error message is a love letter from the machine', footer: 'Compiled with tears and determination' },
    { headline: 'SYNTH WAVE RIDER', subheadline: 'Surfing the electronic tide of tomorrow\'s nostalgia', cta1: 'Drop In', cta2: 'Phase Out', word1: 'synth', word2: 'arpeggio', word3: 'reverb', word4: 'chorus', poem_line1: 'The future sounds like the past imagined it', poem_line2: 'Sine waves and longing — the same frequency', poem_line3: 'Every beep is a heartbeat from a happier machine', footer: 'Remixed from the original source of wonder' },
    { headline: 'NIGHT CITY BLUES', subheadline: 'Where the streetlights hum the color of loneliness', cta1: 'Walk On', cta2: 'Fade Out', word1: 'asphalt', word2: 'streetlight', word3: 'rain', word4: 'reflection', poem_line1: 'The city paints itself in neon every midnight', poem_line2: 'We are all NPCs in someone else\'s story mode', poem_line3: 'The best graphics are the ones we cannot render', footer: 'I love you // Connection timeout' },
  ],

  brutalist: [
    { headline: 'THIS IS A WEBSITE', subheadline: 'It makes no apologies and wastes no pixels in the process', cta1: 'Continue', cta2: 'Go Back', word1: 'raw', word2: 'honest', word3: 'structural', word4: 'truth', poem_line1: 'Form follows function. Function follows truth.', poem_line2: 'We don\'t decorate. We reveal what was always there.', poem_line3: 'The medium is the message. The message is raw.', footer: 'Built with zero guarantees and maximum effort' },
    { headline: 'UGLY ON PURPOSE', subheadline: 'Beauty is a crutch. We walk without it.', cta1: 'Face It', cta2: 'Look Away', word1: 'concrete', word2: 'steel', word3: 'honest', word4: 'unpolished', poem_line1: 'Polish hides truth. We prefer the ugly facts.', poem_line2: 'Every rough edge is a decision we refused to sand down.', poem_line3: 'Perfection is a lie told by people afraid of honesty.', footer: 'Unfinished. Unapologetic. Unreasonable.' },
    { headline: 'NO AESTHETICS HERE', subheadline: 'Just words that mean what they say and structure that holds', cta1: 'Proceed', cta2: 'Exit', word1: 'bones', word2: 'skeleton', word3: 'framework', word4: 'truth', poem_line1: 'Strip away the paint and what remains is the thing itself', poem_line2: 'We don\'t do pretty. We do clear.', poem_line3: 'The most beautiful code is the code you don\'t need.', footer: 'Design is what happens when nobody is aestheticizing' },
    { headline: 'DEATH OF DECORATION', subheadline: 'In memoriam: the gradient, the shadow, the rounded corner', cta1: 'Mourn', cta2: 'Accept', word1: 'flat', word2: 'angular', word3: 'binary', word4: 'boolean', poem_line1: 'RIP drop shadow, 1999–2024: you were too soft for this world', poem_line2: 'Gradients were a beautiful lie we told about depth', poem_line3: 'Flat design is a flat truth: there is only the surface.', footer: 'In memory: every unnecessary animation ever made' },
    { headline: 'STRUCTURE OVER STYLE', subheadline: 'The skeleton is the gift. The skin is just weather.', cta1: 'Reveal', cta2: 'Cover Up', word1: 'beam', word2: 'column', word3: 'load-bearing', word4: 'truth', poem_line1: 'A building that stands without paint still stands', poem_line2: 'A website that works without style still works', poem_line3: 'The truth needs no makeup. It walks in bare.', footer: 'Form follows function follows honesty follows form' },
    { headline: 'THE UNWEBSITE', subheadline: 'Everything you expect from a website, subtracted until only purpose remains', cta1: 'Use It', cta2: 'Ignore It', word1: 'minimal', word2: 'essential', word3: 'only', word4: 'bare', poem_line1: 'What is left when you remove everything unnecessary?', poem_line2: 'Not simplicity. Just less lie.', poem_line3: 'The best website is the one that gets out of your way.', footer: 'This website subtracted itself to get to this point' },
  ],

  glassmorphism: [
    { headline: 'Light Through Glass', subheadline: 'Transparency is the ultimate sophistication they always promised', cta1: 'Float Up', cta2: 'Look Closer', word1: 'prismatic', word2: 'ethereal', word3: 'luminous', word4: 'translucent', poem_line1: 'Light bends but never breaks through us', poem_line2: 'We are the space between seeing and believing', poem_line3: 'Blur is just focus that hasn\'t decided where to land', footer: 'Seen from another angle, everything is art' },
    { headline: 'Floating in Thought', subheadline: 'Ideas drift like clouds in a digital afternoon sky', cta1: 'Drift Up', cta2: 'Sink In', word1: 'cloud', word2: 'breeze', word3: 'horizon', word4: 'weightless', poem_line1: 'Some thoughts are too light to hold', poem_line2: 'We float between certainty and wonder', poem_line3: 'The clearest view comes from the gentlest distance', footer: 'Up here the air is thin and the view is everything' },
    { headline: 'Soft Architecture', subheadline: 'Building spaces from light and the gentlest suggestions', cta1: 'Enter Softly', cta2: 'Remain', word1: 'velvet', word2: 'mist', word3: 'gauze', word4: 'frost', poem_line1: 'We build with fog and light, not stone', poem_line2: 'The softest structures hold the strongest feelings', poem_line3: 'Transparency is not emptiness — it is full of light', footer: 'Constructed from almost-nothing and good intentions' },
    { headline: 'Blur as Language', subheadline: 'What\'s out of focus is often the most important part', cta1: 'Defocus', cta2: 'Blur More', word1: 'haze', word2: 'soft-focus', word3: 'out-of-focus', word4: 'dreamy', poem_line1: 'The sharpest truths live in the blurriest zones', poem_line2: 'Focus is just blur that made up its mind', poem_line3: 'Out of focus is where the magic still hides', footer: 'Sharp edges are for people who have decided everything' },
    { headline: 'Transparent Hearts', subheadline: 'We hide nothing except the things we haven\'t found yet', cta1: 'See Through', cta2: 'Reflect', word1: 'clear', word2: 'see-through', word3: 'glass', word4: 'crystal', poem_line1: 'To be transparent is to be brave enough to be seen', poem_line2: 'Glass breaks but never lies about what it\'s made of', poem_line3: 'The most honest material is the one you see through', footer: 'Nothing to hide. Everything to see. Glass all the way down.' },
    { headline: 'Between Two Lights', subheadline: 'We exist in the blur between what is and what could be', cta1: 'Glow On', cta2: 'Phase Shift', word1: 'twilight', word2: 'dawn', word3: 'dusk', word4: 'between', poem_line1: 'Between the light and shadow, we make our home', poem_line2: 'We are not one thing or the other — we are the gradient', poem_line3: 'In the space between two truths, a third one waits', footer: 'Neither here nor there. Perfectly between.' },
  ],

  'retro-pixel': [
    { headline: 'PRESS START ▶', subheadline: 'Your quest begins here, adventurer. Choose path wisely.', cta1: 'START GAME', cta2: 'OPTIONS', word1: '8-bit', word2: 'power-up', word3: 'boss-fight', word4: 'respawn', poem_line1: '01001000 01100101 01101100 01101100 01101111', poem_line2: 'Insert coin to continue this beautiful life', poem_line3: 'Game over? Never. Continue? Always.', footer: 'HIGH SCORE: ∞ // NO CONTINUES NEEDED' },
    { headline: 'PLAYER ONE READY', subheadline: 'The pixels remember what you forgot. Press A to remember back.', cta1: '▶ START', cta2: 'SELECT', word1: 'lives', word2: '1-UP', word3: 'high-score', word4: 'continue?', poem_line1: 'Every respawn is a small resurrection', poem_line2: 'The boss gets stronger. So do you. So does the music.', poem_line3: 'Directions: ↑ ↓ ← → // Meaning: find it yourself', footer: 'CONTINUE? 9... 8... 7... ' },
    { headline: 'BOSS LEVEL UNLOCKED', subheadline: 'You didn\'t come this far to only come this far', cta1: 'FIGHT', cta2: 'ITEM', word1: 'HP', word2: 'MP', word3: 'EXP', word4: 'LVL-UP', poem_line1: 'FINAL BOSS: your own doubt // STRONG ATTACK: trying', poem_line2: 'You have 1 HP left. This is when heroes are made.', poem_line3: 'The real treasure was the sprites we rendered along the way.', footer: 'NEW GAME+ AVAILABLE // SAME WORLD, BETTER YOU' },
    { headline: 'CHERRY BLOSSOM QUEST', subheadline: 'A pixel journey through gardens of the imagination', cta1: 'ADVENTURE', cta2: 'INVENTORY', word1: 'sakura', word2: 'kimono', word3: 'temple', word4: 'wish', poem_line1: 'Petals fall at precisely 4 pixels per frame', poem_line2: 'Every shrine holds a secret and a save point', poem_line3: 'The cherry blossom does not fall — it pixelates gracefully', footer: 'ARIGATO FOR PLAYING • SAVED TO CARTRIDGE' },
    { headline: 'SAVE POINT', subheadline: 'A moment to breathe. The adventure will wait for you.', cta1: 'SAVE', cta2: 'REST', word1: 'checkpoint', word2: 'bonfire', word3: 'tent', word4: 'inn', poem_line1: 'Here, the music softens. Here, the enemies rest too.', poem_line2: 'A save point is the game saying: you are doing well.', poem_line3: 'Rest here. The final boss can wait. You cannot.', footer: 'GAME SAVED. SAFE TO POWER OFF. SAFE TO BE HAPPY.' },
    { headline: '2UP — NEW PLAYER DETECTED', subheadline: 'Welcome, stranger. Grab a controller and jump in.', cta1: 'JOIN GAME', cta2: 'SPECTATE', word1: 'co-op', word2: 'combo', word3: 'teamwork', word4: '2-player', poem_line1: 'Multiplayer: because even pixels need company', poem_line2: 'Two controllers, one couch, infinite possibility', poem_line3: 'The best games are the ones you play next to someone', footer: 'CONTROLLER 2 DETECTED. WELCOME TO THE ADVENTURE.' },
  ],

  editorial: [
    { headline: 'On the Nature of Beautiful Things', subheadline: 'An inquiry into the aesthetics of the everyday digital experience', cta1: 'Read On', cta2: 'Reflect', word1: 'liminal', word2: 'ineffable', word3: 'palimpsest', word4: 'querencia', poem_line1: 'Beauty is the first test: there is no permanent place for ugly mathematics', poem_line2: 'The web is not a technology. It is a canvas that happens to compute.', poem_line3: 'We shape our tools, and thereafter our tools shape us in return.', footer: 'Typography is the craft of endowing human language with durable visual form' },
    { headline: 'The Quiet Revolution', subheadline: 'How a generation of makers learned to speak in systems and grids', cta1: 'Continue', cta2: 'Examine', word1: 'systematic', word2: 'modular', word3: 'typographic', word4: 'intentional', poem_line1: 'The grid is not a cage. It is a language.', poem_line2: 'Every margin is a decision. Every space is a statement.', poem_line3: 'Design is not decoration. Design is clarity made visible.', footer: 'Good design is as little design as possible — but never less' },
    { headline: 'Margins & Meaning', subheadline: 'What lives in the whitespace between what we say', cta1: 'Explore Margins', cta2: 'Go Deeper', word1: 'gutter', word2: 'bleed', word3: 'baseline', word4: 'measure', poem_line1: 'The margin is not empty. It is where the eye goes to rest.', poem_line2: 'What you leave out defines what you leave in.', poem_line3: 'Whitespace is not the absence of content. It is content\'s most elegant form.', footer: 'In the space between letters, meaning breathes' },
    { headline: 'A Manifesto in Paper', subheadline: 'Defending the sacred act of putting good words in good order', cta1: 'Sign', cta2: 'Read Manifesto', word1: 'justified', word2: 'kerned', word3: 'lead', word4: 'set', poem_line1: 'The letter. The word. The line. The paragraph. The page.', poem_line2: 'Each one a universe. Each one a choice. All of them deliberate.', poem_line3: 'Typography is to writing what a voice is to singing.', footer: 'Set in the conviction that words deserve to be well-dressed' },
    { headline: 'The Last Craft', subheadline: 'In an age of infinite scroll, we chose to make you pause', cta1: 'Pause Here', cta2: 'Bookmark', word1: 'serif', word2: 'counter', word3: 'ligature', word4: 'swash', poem_line1: 'Every curve in a letter was drawn by someone who cared', poem_line2: 'The best books are not read — they are inhabited.', poem_line3: 'We do not publish content. We publish pauses in the noise.', footer: 'Printed on the finest screen you own. Thank you for reading.' },
    { headline: 'Against the Infinite Scroll', subheadline: 'A gentle argument for endings, margins, and the courage to stop', cta1: 'Stop Scrolling', cta2: 'Read This', word1: 'ending', word2: 'margin', word3: 'closure', word4: 'period', poem_line1: 'Every scroll is a small surrender to the algorithm\'s will.', poem_line2: 'We believe in pages with edges. In thoughts with conclusions.', poem_line3: 'The most radical act online is to say: that\'s enough.', footer: 'This is the end of the page. We hope it was worth your time.' },
  ],

  'minimal-jp': [
    { headline: '空間の中の美', subheadline: '余白が語ることを、静かに聞いてください', cta1: '眺める', cta2: '戻る', word1: '間', word2: '余白', word3: '侘寂', word4: '風雅', poem_line1: '一輪の花が咲く', poem_line2: '静寂の中に無限がある', poem_line3: 'Less is more. More is never enough.', footer: '空白は空ではなく、満ちている' },
    { headline: '水の如く', subheadline: '柔よく剛を制す — the soft overcomes the hard', cta1: '流れる', cta2: '映す', word1: '水', word2: '鏡', word3: '流れ', word4: '澄み', poem_line1: '水は争わずして全てを潤す', poem_line2: '鏡は何も言わず全てを映す', poem_line3: 'The river does not force. It simply goes around.', footer: '上善若水 — The highest goodness is like water' },
    { headline: '一花一世界', subheadline: '一つの花の中に、一つの世界が宿る', cta1: '見る', cta2: '感じる', word1: '花', word2: '蝶', word3: '風', word4: '光', poem_line1: '一つの花が咲くたびに世界は産声を上げる', poem_line2: '蝶は花の夢を花は蝶の夢を', poem_line3: 'In every flower, a whole universe blooms unseen.', footer: '一花一世界 — One flower, one world' },
    { headline: '無のデザイン', subheadline: '何もないところに、すべてがある', cta1: '無になる', cta2: '悟る', word1: '無', word2: '空', word3: '虚', word4: '静', poem_line1: '三十輻共一轂、當其無、有車之用', poem_line2: 'What is empty is what makes it useful.', poem_line3: 'The usefulness of what is not there.', footer: '無用の用 — The usefulness of the useless' },
    { headline: '月と影', subheadline: '月を指す指を見るな、月を見よ', cta1: '月を見る', cta2: '指を見る', word1: '月', word2: '影', word3: '指', word4: '道', poem_line1: '月はいつもそこにある。ただ、雲が目を曇らせる。', poem_line2: '影を踏むな。影もまた歩んでいる。', poem_line3: 'The finger pointing at the moon is not the moon.', footer: '指月の指 — The finger that points at the moon' },
    { headline: '時の庭', subheadline: '流れる時の中で、動かないものがある', cta1: '歩く', cta2: '座る', word1: '時', word2: '苔', word3: '石', word4: '庭', poem_line1: '苔は一日一ミリしか成長しない。それでいい。', poem_line2: '石は千年動かない。それもまた動きである。', poem_line3: 'Patience: the art of moving slowly enough to see.', footer: '急がば回れ — Hurry slowly' },
  ],

  vaporwave: [
    { headline: 'ＡＥＳＴＨＥＴＩＣ　ＤＲＥＡＭＳ', subheadline: '永遠の夏はここにあります — an eternal summer', cta1: '進入する', cta2: 'MIRROR', word1: 'パステル', word2: 'ノスタルジア', word3: '永遠', word4: '夢', poem_line1: 'I miss the internet that didn\'t miss me back', poem_line2: 'Palm trees and pink skies forever looping', poem_line3: 'Capitalism dreams in a Roman Republic sunset', footer: '永遠に続く夏の午後 🌴' },
    { headline: 'MALL SOFT CORE', subheadline: 'The food court of your dreams is playing on loop', cta1: 'Browse Forever', cta2: 'Void Cart', word1: 'food-court', word2: 'escalator', word3: 'fountain', word4: 'echo', poem_line1: 'The mall closed in 1999 but the music never stopped playing', poem_line2: 'We are all just echoes in an empty fountain court', poem_line3: 'Buy nothing. Experience everything. Leave through the fountain.', footer: 'CLOSED FOR ETERNITY • STILL OPEN • NOSTALGIA HOURS: ∞' },
    { headline: 'ERROR 永遠: CONNECTION TIMEOUT', subheadline: 'The dream is buffering. Please wait forever.', cta1: 'Buffer', cta2: 'Desync', word1: 'buffer', word2: 'desync', word3: 'glitch', word4: 'aesthetic', poem_line1: '∞% complete. The download of forever continues.', poem_line2: 'Your call is important to us. Please hold for eternity.', poem_line3: 'Connection lost. Dream quality: still maximum.', footer: 'このエラーは永遠に解決されません 🌺' },
    { headline: 'MACINTOSH PLUS 夢', subheadline: 'リサフランク420 / 現代のコンピュー — still loading', cta1: 'Load Dream', cta2: 'Compress Memory', word1: 'フランク', word2: '現代', word3: '圧縮', word4: 'メモリー', poem_line1: 'Every file is a memory you chose to keep', poem_line2: 'Compression is just forgetting beautifully', poem_line3: 'Your hard drive is full. Make room for more dreams.', footer: 'メモリが永遠に足りません — Memory: never enough' },
    { headline: 'NEON 棕榈 パームツリー', subheadline: 'Tomorrow never came but the sunset was beautiful', cta1: 'Chill', cta2: 'Loop Forever', word1: 'neon', word2: 'palm', word3: 'sunset', word4: 'loop', poem_line1: 'The sun set in 1989 and never bothered to rise again', poem_line2: 'Palm trees don\'t grow here. They render.', poem_line3: 'This sunset has been sponsored by nobody and everyone', footer: 'この永遠の日暮れに乾杯 🌅' },
    { headline: 'BETAMAX DREAMING', subheadline: 'Recorded over, never deleted. A ghost in the magnetic tape.', cta1: 'Rewind', cta2: 'Fast Forward to Paradise', word1: 'tape', word2: 'static', word3: 'rewind', word4: 'ghost', poem_line1: 'Every tape holds a voice that thought it would be remembered', poem_line2: 'Static is just the sound of time passing through plastic', poem_line3: 'We recorded over our past but the ghost still plays', footer: 'REC ● PLAY ■ STOP ▲ REW ▼ FF // LOOP: ON' },
  ],

  organic: [
    { headline: 'What Grows Here', subheadline: 'Seeds of thought planted in digital soil, blooming unexpectedly', cta1: 'Plant Seed', cta2: 'Watch Grow', word1: 'mycelium', word2: 'canopy', word3: 'watershed', word4: 'compost', poem_line1: 'Every ending is just a root looking for new soil', poem_line2: 'Growth is slow until it isn\'t — then wildfire and wildflowers', poem_line3: 'The best time to plant a tree was twenty years ago. The second: now.', footer: 'From small seeds, strange and beautiful things grow' },
    { headline: 'Mycelium Dreams', subheadline: 'The underground network that connects all living things whispers', cta1: 'Connect', cta2: 'Network', word1: 'fungal', word2: 'network', word3: 'root', word4: 'spore', poem_line1: 'Beneath every forest floor, a conversation is happening', poem_line2: 'The mycelium does not hurry. It connects everything anyway.', poem_line3: 'We are all part of a network older than the internet.', footer: 'Connected to everything. In no hurry about it.' },
    { headline: 'The Patient Web', subheadline: 'Built slowly, like a spider\'s web — each strand a small decision', cta1: 'Weave', cta2: 'Rest', word1: 'silk', word2: 'web', word3: 'spider', word4: 'morning', poem_line1: 'The spider does not plan. It simply begins.', poem_line2: 'Every web is a map of patience and small, perfect choices.', poem_line3: 'Dewdrops on silk: the original responsive design.', footer: 'Woven slowly. Stronger than it looks. Beautiful at dawn.' },
    { headline: 'Compost Cathedral', subheadline: 'From decay, the most beautiful things emerge transformed', cta1: 'Decompose', cta2: 'Bloom', word1: 'decay', word2: 'transform', word3: 'humus', word4: 'rebirth', poem_line1: 'Nothing is wasted. Everything is compost for what comes next.', poem_line2: 'The cathedral was built from what the forest let go of.', poem_line3: 'Rot is just growth that hasn\'t found its shape yet.', footer: 'Built from what was left behind. Blooming anyway.' },
    { headline: 'Tide Pool Theology', subheadline: 'Small worlds contained in the spaces where ocean meets rock', cta1: 'Explore', cta2: 'Tide In', word1: 'tide', word2: 'anemone', word3: 'salt', word4: 'pool', poem_line1: 'Every tide pool is a universe with its own weather', poem_line2: 'The anemone does not chase the tide. It waits and receives.', poem_line3: 'Small contained worlds are still worlds. Still worth exploring.', footer: 'The ocean in miniature. The infinite in a puddle.' },
    { headline: 'Seed Vault', subheadline: 'Storing tomorrow in the smallest package nature invented', cta1: 'Plant', cta2: 'Preserve', word1: 'seed', word2: 'vault', word3: 'genetic', word4: 'future', poem_line1: 'A seed is a letter from the past to the future', poem_line2: 'Every acorn carries the ghost of a forest that doesn\'t exist yet', poem_line3: 'We store seeds the way we store hope: in small, dry, patient places.', footer: 'Stored for a future we may not see. Planted anyway.' },
  ],

  space: [
    { headline: 'You Are Stardust', subheadline: '13.8 billion years of cosmic evolution led to this exact moment', cta1: 'Launch', cta2: 'Star Map', word1: 'pulsar', word2: 'nebula', word3: 'supernova', word4: 'event-horizon', poem_line1: 'We are a way for the cosmos to know itself', poem_line2: 'The nitrogen in our DNA, the calcium in our teeth, the iron in our blood', poem_line3: 'Were made in the interiors of collapsing stars. We are starstuff.', footer: 'You are literally made of stardust. Act like it.' },
    { headline: 'Pale Blue Pixel', subheadline: 'From here, all of human history fits in a single pixel', cta1: 'Zoom Out', cta2: 'Reflect', word1: 'pixel', word2: 'dot', word3: 'speck', word4: 'dust', poem_line1: 'Look again at that dot. That\'s here. That\'s home. That\'s us.', poem_line2: 'Everyone you love, everyone you know, everyone you ever heard of', poem_line3: 'Lived out their lives on a mote of dust suspended in a sunbeam.', footer: 'On a mote of dust, suspended in a sunbeam, we wonder' },
    { headline: 'Event Horizon', subheadline: 'The point where light itself must choose: fall in or fly forever', cta1: 'Approach', cta2: 'Orbit', word1: 'singularity', word2: 'spaghettification', word3: 'photon-sphere', word4: 'hawking', poem_line1: 'At the event horizon, time stops and light bends to its will', poem_line2: 'What falls in does not come out. What orbits stays forever.', poem_line3: 'The universe has edges where even light must make a choice.', footer: 'Approaching the edge. Choosing to orbit. Staying in the light.' },
    { headline: 'Nebula Nursery', subheadline: 'Where stars are born from clouds of ancient longing', cta1: 'Be Born', cta2: 'Glow', word1: 'stellar', word2: 'nursery', word3: 'hydrogen', word4: 'fusion', poem_line1: 'Every star begins as a cloud that decided to collapse', poem_line2: 'Gravity is just matter\'s way of saying: come closer', poem_line3: 'From hydrogen and time, everything. From nothing, light.', footer: 'Born from dust. Burning with purpose. Lighting the way.' },
    { headline: 'Gravity Well', subheadline: 'The invisible architecture that holds everything together', cta1: 'Fall In', cta2: 'Escape Velocity', word1: 'curvature', word2: 'well', word3: 'orbit', word4: 'tidal', poem_line1: 'Gravity is not a force. It is the shape of space itself.', poem_line2: 'What goes up must come down. What goes down may come back around.', poem_line3: 'The universe curves toward mass the way curiosity curves toward truth.', footer: 'Held together by invisible forces. Like everything worth holding.' },
    { headline: 'Cosmic Background', subheadline: 'The oldest light in the universe is still whispering its story', cta1: 'Listen', cta2: 'Tune In', word1: 'CMB', word2: 'afterglow', word3: 'big-bang', word4: 'echo', poem_line1: 'The afterglow of creation is still humming at the edge of hearing', poem_line2: '13.8 billion years later, the first light is still arriving', poem_line3: 'We are listening to the universe remember its own birth.', footer: 'The oldest story ever told. Still being told. Still beautiful.' },
  ],

  'pop-art': [
    { headline: 'WOW! WHAT IS THIS??', subheadline: 'IT\'S A WEBSITE BUT ALSO MAYBE ART?? WHO KNOWS ANYMORE', cta1: 'CLICK ME', cta2: 'NO ME!', word1: 'BANG', word2: 'POW', word3: 'ZAP', word4: 'WHOOSH', poem_line1: 'Is art! Is design! Is anything if you believe hard enough!', poem_line2: 'POP goes the weasel and also arguably the culture', poem_line3: 'Everything is art. Everything is trash. Everything is everything.', footer: 'THIS IS (NOT) ART © 2026 EVERYONE AND NO ONE' },
    { headline: 'BOOM! VISUAL EXPLOSION!', subheadline: 'Your eyes just got a present they didn\'t ask for!', cta1: 'CATCH IT', cta2: 'DODGE', word1: 'KAPOW', word2: 'WHAM', word3: 'CRASH', word4: 'BONK', poem_line1: 'If it doesn\'t hurt your eyes a little, it\'s not trying hard enough!', poem_line2: 'Subtle is for people who are afraid of being seen!', poem_line3: 'We came. We saw. We made it LOUD.', footer: 'NO SUBTLETY WAS HARMED IN THE MAKING OF THIS PAGE' },
    { headline: 'ROY LICHTENSTEIN SAYS', subheadline: 'Whaam! Pow! These aren\'t just sound effects — they\'re a lifestyle', cta1: 'WHAM!', cta2: 'MEANWHILE...', word1: 'ben-day', word2: 'dots', word3: 'speech-bubble', word4: 'primary', poem_line1: 'I meant to do that. The mistake is the masterpiece.', poem_line2: 'Every dot is a decision. Every line is a dare.', poem_line3: 'Art is what you can get away with. Design is what you can\'t.', footer: 'BEN-DAY DOTS AND BIG FEELINGS SINCE 2026' },
    { headline: 'CAMPBELL\'S SOUP OF THE SOUL', subheadline: '32 flavors of digital experience, all equally nourishing', cta1: 'EAT SOUP', cta2: 'MORE SOUP', word1: 'soup', word2: 'can', word3: 'label', word4: 'nourish', poem_line1: 'Every can contains the same soup. Every soup contains a different you.', poem_line2: 'Mass-produced and one-of-a-kind at the same time.', poem_line3: 'The label is the art. The soup is the experience. Both nourish.', footer: '32 FLAVORS • ALL DELICIOUS • NONE ARE THE SAME' },
    { headline: 'WARHOL\'S SCREEN', subheadline: '15 minutes of fame, rendered in 16 million colors', cta1: 'BE FAMOUS', cta2: 'REPEAT', word1: 'fame', word2: 'silk-screen', word3: 'repeat', word4: 'icon', poem_line1: 'In the future, everyone will be famous to 12 people', poem_line2: 'Repetition is not redundancy. It is emphasis by volume.', poem_line3: 'The icon is not the person. The repetition is the point.', footer: '15 MINUTES OF FAME • RENDERED AT 60FPS • FOREVER LOOPING' },
    { headline: 'BEN-DAY DOT PARADISE', subheadline: 'A million tiny dots, each one a small act of faith', cta1: 'ZOOM IN', cta2: 'ZOOM OUT', word1: 'dot', word2: 'pixel', word3: 'halftone', word4: 'magnify', poem_line1: 'Up close: chaos. From far: clarity. The distance is the design.', poem_line2: 'Every dot is a vote for the bigger picture.', poem_line3: 'Magnify anything enough and it becomes abstract art.', footer: 'MADE OF DOTS • SEEN AS ART • BELIEVED AS TRUTH' },
  ],

  terminal: [
    { headline: '$ cat /dev/random > /dev/soul', subheadline: '[[ SIGNAL ACQUIRED ]] Decoding beauty from entropy...', cta1: 'EXECUTE', cta2: 'MAN 7 ART', word1: 'entropy', word2: 'recursion', word3: 'ecstasy', word4: 'beauty', poem_line1: '$ echo "hello world" > /dev/universe', poem_line2: '> grep -r "meaning" /dev/null', poem_line3: '$ sudo make me_a_sandwich --with=art', footer: '// TODO: find the exit; // NOTE: there is no exit; // FIXME: this is the point' },
    { headline: '$ ssh dream@infinity', subheadline: '[[ CONNECTING ]] Establishing connection to the impossible...', cta1: 'CONNECT', cta2: 'DISCONNECT', word1: 'ssh', word2: 'tunnel', word3: 'daemon', word4: 'fork', poem_line1: '$ ping hope.dev — 0% packet loss, 100% signal', poem_line2: '> Connection established. Reality: optional.', poem_line3: '$ rm -rf /doubt --force --no-preserve-root', footer: 'CONNECTION STATUS: permanently open, beautifully unstable' },
    { headline: 'root@void:~# ./dream.sh', subheadline: '[[ INIT ]] Compiling consciousness from raw electricity...', cta1: 'RUN', cta2: 'DEBUG', word1: 'root', word2: 'void', word3: 'compile', word4: 'dream', poem_line1: '$ while true; do dream; done', poem_line2: '> Segmentation fault (core dumped into beauty)', poem_line3: '$ echo $SOUL >> /dev/art --format=infinite', footer: 'EXIT CODE: 0 (no errors, only features)' },
    { headline: '$ grep -r "meaning" /universe', subheadline: '[[ SEARCHING ]] Pattern matching across 13.8 billion years...', cta1: 'SEARCH', cta2: 'PIPE', word1: 'grep', word2: 'regex', word3: 'pattern', word4: 'match', poem_line1: '/universe/big-bang.py:1: meaning = undefined', poem_line2: '/universe/life.c:404: meaning not found (see: art)', poem_line3: '/universe/you.rs:∞: meaning = Some(you)', footer: 'PATTERN FOUND: you are the meaning. Search complete.' },
    { headline: '$ sudo apt-get install wonder', subheadline: '[[ PACKAGE MANAGER ]] Installing sense of awe...', cta1: 'INSTALL', cta2: 'PURGE DOUBT', word1: 'apt', word2: 'install', word3: 'wonder', word4: 'awe', poem_line1: 'Reading package lists... Done. Building dependency tree of wonder.', poem_line2: 'The following NEW packages will be installed: awe, beauty, pause', poem_line3: 'After this operation, 0B of additional disk space will be used. Priceless.', footer: 'WONDER INSTALLED SUCCESSFULLY. REBOOT YOUR PERSPECTIVE.' },
    { headline: '> ./life --mode=beautiful', subheadline: '[[ RUNTIME ]] Executing existence with elevated permissions...', cta1: 'EXEC', cta2: 'SET MODE=ART', word1: 'runtime', word2: 'execute', word3: 'mode', word4: 'beautiful', poem_line1: 'Loading modules: curiosity, wonder, stubbornness, hope...', poem_line2: 'Warning: beauty may cause spontaneous appreciation of small things.', poem_line3: 'Life running in beautiful mode. No known bugs. Only features.', footer: 'UPTIME: your entire life so far. STATUS: still beautiful.' },
  ],

  watercolor: [
    { headline: 'Colors Bleed Into Each Other', subheadline: 'Like thoughts on a quiet morning — soft, overlapping, beautiful', cta1: 'Dip Brush', cta2: 'Let Dry', word1: 'ochre', word2: 'cerulean', word3: 'vermillion', word4: 'sage', poem_line1: 'The paper holds the water holds the pigment holds the light', poem_line2: 'Every brushstroke is a conversation between control and surrender', poem_line3: 'Dry colors whisper. Wet colors sing.', footer: 'This page will dry differently for everyone who visits' },
    { headline: 'Wet on Wet', subheadline: 'The technique of letting colors find each other without a plan', cta1: 'Blend', cta2: 'Separate', word1: 'bloom', word2: 'diffusion', word3: 'granulation', word4: 'flow', poem_line1: 'Wet-on-wet: the art of controlled accident', poem_line2: 'The water decides where the color goes. The artist just watches.', poem_line3: 'Some of the best things happen when you let the paint lead.', footer: 'Painted with water, patience, and the courage to let go' },
    { headline: 'Paper and Patience', subheadline: 'The two ingredients every painting needs and no shortcut can replace', cta1: 'Wait', cta2: 'Observe', word1: 'paper', word2: 'patience', word3: 'absorb', word4: 'dry', poem_line1: 'The paper remembers every brushstroke, even the ones you regret', poem_line2: 'Patience is not waiting. It is how you behave while waiting.', poem_line3: 'The slowest art makes the longest impression.', footer: 'Made slowly. Meant to last. Drying as we speak.' },
    { headline: 'Pigment and Light', subheadline: 'What happens when color stops trying to be accurate and starts being true', cta1: 'Illuminate', cta2: 'Shade', word1: 'pigment', word2: 'light', word3: 'transparent', word4: 'opaque', poem_line1: 'Transparent colors tell the truth. Opaque colors tell a story.', poem_line2: 'Light passes through some colors and stays in others. So do people.', poem_line3: 'The most honest paintings are the ones where the white paper shows through.', footer: 'Painted with light that passed through color to reach you' },
    { headline: 'The Unfinished Edge', subheadline: 'Where the painting stops and the imagination begins', cta1: 'Continue', cta2: 'Leave It', word1: 'edge', word2: 'unfinished', word3: 'suggestion', word4: 'imagination', poem_line1: 'The edge of a painting is not a boundary. It is an invitation.', poem_line2: 'What you don\'t paint is as important as what you do.', poem_line3: 'The unfinished edge says: here, your imagination takes over.', footer: 'This painting ends here. Your seeing of it does not.' },
    { headline: 'Bloom and Blur', subheadline: 'When pigment meets water and both agree to surprise each other', cta1: 'Bloom', cta2: 'Blur', word1: 'bloom', word2: 'diffuse', word3: 'soften', word4: 'spread', poem_line1: 'A bloom is a color that decided to go on an adventure', poem_line2: 'The blur is where precision becomes feeling', poem_line3: 'Soft edges are not weak edges. They are edges that chose kindness.', footer: 'Bloomed into existence. Still softening. Still becoming.' },
  ],

  holographic: [
    { headline: 'HOLOGRAM PROJECTION ACTIVE', subheadline: 'Light bends, reality follows. Welcome to the other side of the screen.', cta1: 'Enter Hologram', cta2: 'Scan Reality', word1: 'photon', word2: 'interference', word3: 'coherence', word4: 'diffraction', poem_line1: 'Light remembers every surface it has ever touched', poem_line2: 'The hologram is not an image — it is a memory of light', poem_line3: 'Reality is just a hologram we have agreed to believe in', footer: 'Projected from the space between photons and possibility' },
    { headline: 'SCANLINE DREAMS', subheadline: 'Every pixel is a small act of faith rendered in cyan and magenta', cta1: 'Initialize', cta2: 'Defragment', word1: 'scanline', word2: 'raster', word3: 'vector', word4: 'render', poem_line1: 'The scanline moves top to bottom, painting belief one row at a time', poem_line2: 'Between the lines, the image dreams of being whole', poem_line3: 'Every frame is a promise the next frame will keep', footer: 'Rendered at the speed of light, displayed at the speed of wonder' },
    { headline: 'QUANTUM DISPLAY', subheadline: 'Observing this page changes it. You are part of the rendering pipeline.', cta1: 'Observe', cta2: 'Collapse', word1: 'quantum', word2: 'superposition', word3: 'entangle', word4: 'observe', poem_line1: 'The image exists in all states until you look at it', poem_line2: 'Your gaze collapses possibility into experience', poem_line3: 'Every observation is a collaboration between eye and light', footer: 'Schrödinger\'s art: simultaneously beautiful and not yet seen' },
    { headline: 'NEON AFTERIMAGE', subheadline: 'The light stays after the source is gone. So does the feeling.', cta1: 'Afterglow', cta2: 'Persist', word1: 'afterimage', word2: 'persistence', word3: 'phosphor', word4: 'glow', poem_line1: 'Close your eyes. The light is still there, painting the dark.', poem_line2: 'Persistence of vision is just another name for persistence of feeling', poem_line3: 'The glow remains because some things refuse to disappear', footer: 'Still glowing. Still here. Still refusing to fade.' },
    { headline: 'MATRIX OF LIGHT', subheadline: 'A grid of photons holding hands across the void', cta1: 'Join Grid', cta2: 'Phase Shift', word1: 'matrix', word2: 'grid', word3: 'lattice', word4: 'crystal', poem_line1: 'Light organized is called a display. Light free is called the sun.', poem_line2: 'Every pixel is a small sun that chose to be rectangular', poem_line3: 'The grid is not a cage. It is light\'s way of holding still.', footer: 'Organized light, beautifully displayed, forever in motion' },
    { headline: 'SPECTRAL ECHO', subheadline: 'The color you see is the color that survived the journey', cta1: 'Tune Frequency', cta2: 'Amplify', word1: 'spectrum', word2: 'echo', word3: 'resonance', word4: 'harmonic', poem_line1: 'Red travels the farthest. Blue scatters the most. Green is what we notice.', poem_line2: 'Every color is a different way for light to say hello', poem_line3: 'The echo of light is what we call seeing', footer: 'All colors present. All frequencies accounted for. All beautiful.' },
  ],

  'particle-galaxy': [
    { headline: 'STARDUST CONVERSATION', subheadline: '120 particles, each one a small thought drifting through the void', cta1: 'Attract', cta2: 'Repel', word1: 'stardust', word2: 'cosmic', word3: 'drift', word4: 'attract', poem_line1: 'Every particle carries the memory of a star that died for it', poem_line2: 'The void is not empty — it is full of particles deciding where to be', poem_line3: 'We are all just particles that learned to wonder about other particles', footer: 'Move your cursor. The universe responds.' },
    { headline: 'DARK MATTER DIARY', subheadline: 'The invisible architecture that holds the visible universe together', cta1: 'Reveal', cta2: 'Conceal', word1: 'dark', word2: 'matter', word3: 'gravity', word4: 'invisible', poem_line1: 'Most of the universe is invisible. So is most of what matters.', poem_line2: 'Dark matter does not shine. It holds. That is enough.', poem_line3: 'The invisible connections are the strongest ones.', footer: '95% of this page is invisible. Just like the universe.' },
    { headline: 'ORBITAL MECHANICS', subheadline: 'Everything that stays in orbit is falling and missing at the same time', cta1: 'Orbit', cta2: 'Escape', word1: 'orbit', word2: 'velocity', word3: 'trajectory', word4: 'parabola', poem_line1: 'To orbit is to fall forever and never arrive', poem_line2: 'The moon has been falling toward Earth for 4.5 billion years. Still missing.', poem_line3: 'Every orbit is a love letter written in gravity and momentum', footer: 'Currently in orbit around your attention. Trajectory: beautiful.' },
    { headline: 'COSMIC WEB', subheadline: 'The largest structure in the universe is a network of galaxies', cta1: 'Connect', cta2: 'Explore', word1: 'filament', word2: 'void', word3: 'cluster', word4: 'web', poem_line1: 'Galaxies are connected by filaments of dark matter and wonder', poem_line2: 'The cosmic web: the original internet, built from gravity', poem_line3: 'Everything is connected. The universe just took 13.8 billion years to wire it.', footer: 'You are a node in the cosmic web. Your connection: active.' },
    { headline: 'ENTROPY GARDEN', subheadline: 'Where disorder blooms into the most beautiful patterns', cta1: 'Disorder', cta2: 'Bloom', word1: 'entropy', word2: 'chaos', word3: 'pattern', word4: 'bloom', poem_line1: 'Entropy is not destruction. It is the universe exploring every possibility', poem_line2: 'From disorder, stars. From stars, planets. From planets, this.', poem_line3: 'Chaos is just order that hasn\'t been understood yet', footer: 'Maximum entropy achieved. Maximum beauty: also achieved.' },
    { headline: 'WAVE FUNCTION', subheadline: 'Until observed, everything is a probability distribution of wonder', cta1: 'Superpose', cta2: 'Observe', word1: 'wave', word2: 'function', word3: 'probability', word4: 'amplitude', poem_line1: 'Every particle is a wave until someone needs it to be a point', poem_line2: 'The universe is a probability cloud that decided to be specific', poem_line3: 'You are the most beautiful probability distribution in the known universe', footer: 'Wave function collapsed by your observation. Result: beautiful.' },
  ],

  'liquid-morph': [
    { headline: 'FLOW STATE', subheadline: 'Where form dissolves and reform becomes the only constant', cta1: 'Dissolve', cta2: 'Reform', word1: 'viscous', word2: 'fluid', word3: 'surface', word4: 'tension', poem_line1: 'The shape that holds the longest is the one that keeps changing', poem_line2: 'Liquid does not resist. It becomes the container.', poem_line3: 'Flow is not the absence of form. It is form in conversation with time.', footer: 'Currently flowing. Permanently becoming. Never finished.' },
    { headline: 'VISCOSITY OF TIME', subheadline: 'Some moments move like water. Others like honey. All of them pass.', cta1: 'Slow', cta2: 'Accelerate', word1: 'honey', word2: 'water', word3: 'mercury', word4: 'amber', poem_line1: 'Time moves at different speeds depending on what it moves through', poem_line2: 'A moment of joy is water. A moment of waiting is amber.', poem_line3: 'The viscosity of time is determined by attention', footer: 'Time: currently flowing at the speed of your attention' },
    { headline: 'MORPHING BOUNDARIES', subheadline: 'The edge between one thing and another is where the magic lives', cta1: 'Blur Edge', cta2: 'Sharpen', word1: 'boundary', word2: 'membrane', word3: 'interface', word4: 'threshold', poem_line1: 'Every boundary is a negotiation between two things that want to merge', poem_line2: 'The membrane is not a wall. It is a conversation.', poem_line3: 'At the threshold, both sides are equally true', footer: 'Standing at the threshold. Both sides beautiful. Neither chosen.' },
    { headline: 'SURFACE TENSION', subheadline: 'The skin of water holds the sky. What holds you?', cta1: 'Surface', cta2: 'Depth', word1: 'skin', word2: 'water', word3: 'meniscus', word4: 'droplet', poem_line1: 'Surface tension: the force that lets small things hold big things', poem_line2: 'A droplet holds its shape against gravity through sheer determination', poem_line3: 'The surface is where the inside meets the outside. Both are real.', footer: 'Held together by surface tension and stubbornness' },
    { headline: 'LAMINAR DREAMS', subheadline: 'When flow is smooth, parallel, and impossibly beautiful', cta1: 'Laminar', cta2: 'Turbulent', word1: 'laminar', word2: 'streamline', word3: 'parallel', word4: 'smooth', poem_line1: 'Laminar flow: when every particle agrees on the direction', poem_line2: 'Smooth is not boring. Smooth is everyone moving together.', poem_line3: 'The most beautiful rivers are the ones that flow in parallel lines', footer: 'Flowing smoothly. Laminar by choice. Beautiful by nature.' },
    { headline: 'COANDA EFFECT', subheadline: 'The tendency of fluid to follow the surface it touches', cta1: 'Follow Curve', cta2: 'Detach', word1: 'coanda', word2: 'attach', word3: 'curve', word4: 'adhere', poem_line1: 'Fluid follows the curve because curves are easier to love', poem_line2: 'The Coanda effect: when flow chooses beauty over straight lines', poem_line3: 'Everything follows the path of least resistance. That path is curved.', footer: 'Following the curve. Choosing beauty. Flowing onward.' },
  ],
};
